openapi: 3.0.2
info:
  title: Tracing App Backend API
  version: 0.0.1
servers:
  - url: "http://localhost:3000"
    description: Development server
paths:
  /locations/{userId}/:
    get:
      description: Returns the list of locations the user has visited
      responses:
        "200":
          description: JSON array with GeoJSON Points
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GeoJSONPoint"
    post:
      description: "Adds location records"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/GeoJSONPoint"
      responses:
        "200":
          description: OK
    parameters:
      - name: userId
        in: path
        required: true
        description: The id of the user
        schema:
          $ref: "#/components/schemas/userId"
components:
  schemas:
    GeoJSONPoint:
      type: object
      description: GeoJSON Point2D
      example:
        location:
          type: "Point"
          coordinates:
            - 8.68
            - 50.10
      properties:
        location:
          type: object
          properties:
            type:
              type: string
              enum:
                - Point
            coordinates:
              type: array
              items:
                type: number
                maxItems: 2
                minItems: 2
    userId:
      type: integer
      format: int64
